### ISSUE TITLE
Mongoose schema for exercise

### ISSUE THREAD

**Issue by Eduardo-YGIAH** [Eduardo-YGIAH/Fitness-tracker#3]
# Proposed Task
Build a Mongoose schema for exercise.
# Related to issue
#2 
# Task description
Set up a schema for exercise.
It should have:
- [ ] type, with 2 possible values "resistance" or "cardio" - is required.
- [ ] name, string - is required.
- [ ] duration, number - is required (in minutes)
- [ ] weight, number - optional (in minutes)
- [ ] reps, number - optional ( in minutes)
- [ ] sets, number - optional (in minutes)
